import React from 'react'
import Head from 'next/head'

interface Props {
    title?: string,
    keywords?: string,
    description?: string 
}

const Meta = ({ 
    title = "Up Pose", 
    keywords = "models, photography, freelance", 
    description = "find freelance photography and models for your brand"
    }: Props
) => {
    return (
        <Head>
            <meta name="keywords" content={keywords}/>
            <meta name="description" content={description} />
            <meta charSet="utf-8" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            {/* <link rel="preconnect" href="https://fonts.gstatic.com" /> */}
            <title>{title}</title>
        </Head>
    )
}

export default Meta
